// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAhhTIw9rKpyffDJwyqVGTXf3Ru2EIr-8',
    appId: '1:149731756482:web:277c7a1d545050d117ae5b',
    messagingSenderId: '149731756482',
    projectId: 'tinitz-display-9fc48',
    authDomain: 'tinitz-display-9fc48.firebaseapp.com',
    storageBucket: 'tinitz-display-9fc48.appspot.com',
    measurementId: 'G-358RB29QS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm9YIYwb0kCEB1x-_RsVQEYF0coyG2pbk',
    appId: '1:149731756482:android:42432231273a87f017ae5b',
    messagingSenderId: '149731756482',
    projectId: 'tinitz-display-9fc48',
    storageBucket: 'tinitz-display-9fc48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJHBvjLedHuXy36rEK8rBV2SdDHUjZc6M',
    appId: '1:149731756482:ios:6e524332cb7a030317ae5b',
    messagingSenderId: '149731756482',
    projectId: 'tinitz-display-9fc48',
    storageBucket: 'tinitz-display-9fc48.appspot.com',
    iosBundleId: 'com.example.queingDisplay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJHBvjLedHuXy36rEK8rBV2SdDHUjZc6M',
    appId: '1:149731756482:ios:3747a5d730b96d4717ae5b',
    messagingSenderId: '149731756482',
    projectId: 'tinitz-display-9fc48',
    storageBucket: 'tinitz-display-9fc48.appspot.com',
    iosBundleId: 'com.example.queingDisplay.RunnerTests',
  );
}
